apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: chz5h1zfb-nodejs 
  janus-idp.io/tekton: chz5h1zfb-nodejs
  backstage.io/kubernetes-id: chz5h1zfb-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: chz5h1zfb-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  